title: "OSRP"
description: "Outer Science Research Project"
baseurl: ""
url: ""

lowercase: false
color_bg: var(--oc-gray-9)
color_punct: var(--oc-green-9)
color_keyval: var(--oc-green-4)
color_hover: var(--oc-green-5)
show_quotes: true
show_commas: true
target: "_blank"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
